#!/usr/bin/env python3
"""Generate the four root GitHub Pages files from frozen H55 evidence."""

from __future__ import annotations

import hashlib
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "evidence/results/h55s1-evaluation-20261007.json"
UNIQUENESS = ROOT / "evidence/results/h55s1-full-corpus-check-20261007.json"
PRIOR_RECEIPT = ROOT / "evidence/results/h55-prior-corpus-receipt-20261007.json"

CSS = """/* Generated by scripts/build_h55_site.py */
:root{--ink:#17252b;--muted:#52666d;--paper:#f4f1e8;--card:#fffef9;--line:#cdd9d5;--navy:#102f3a;--teal:#00695d;--teal-soft:#dcefe9;--amber:#a45b12;--amber-soft:#fff0d8;--red:#8d2f2a;--red-soft:#f9e5df;--blue:#164b66;--shadow:0 14px 38px rgba(16,47,58,.08)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.62 system-ui,-apple-system,"Segoe UI",sans-serif}a{color:#00606b;text-underline-offset:3px}.shell{width:min(1100px,calc(100% - 40px));margin:auto}.site-head{background:var(--navy);color:white;border-bottom:4px solid #d0934d}.nav{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:17px 0}.brand{color:#fff;text-decoration:none;font-weight:850;letter-spacing:.04em}.links{display:flex;gap:18px;flex-wrap:wrap}.links a{color:#d7e9e5;font-size:.92rem}.hero{background:var(--navy);color:white;padding:52px 0 58px}.hero-grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(270px,.65fr);gap:28px;align-items:center}.eyebrow{text-transform:uppercase;letter-spacing:.14em;font-weight:850;font-size:.74rem;color:#cc9a63}.hero h1,.pagehead h1{letter-spacing:-.035em;line-height:1.04;margin:.18em 0 .35em}.hero h1{font-size:clamp(2.4rem,6vw,4.4rem);max-width:820px}.hero p{color:#d8e7e3;font-size:1.08rem;max-width:760px}.download{display:inline-flex;align-items:center;justify-content:center;background:#e0a25b;color:#15272c;text-decoration:none;font-weight:900;padding:14px 18px;border-radius:9px;box-shadow:0 7px 18px rgba(0,0,0,.18)}.download:hover{background:#efb873}.download.alt{background:transparent;color:white;border:1px solid #88a39d;box-shadow:none}.actions{display:flex;flex-wrap:wrap;gap:11px;margin-top:25px}.hero-card{background:#fdf9ed;color:var(--ink);padding:21px;border-radius:13px;border:1px solid #dbc7a4}.hero-card strong{display:block;font-size:1.45rem;color:var(--red)}.hero-card p{color:var(--ink);font-size:.95rem;margin:.5em 0 0}.main{padding:34px 0 72px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:18px}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:22px;box-shadow:var(--shadow)}.span-12{grid-column:span 12}.span-8{grid-column:span 8}.span-7{grid-column:span 7}.span-6{grid-column:span 6}.span-5{grid-column:span 5}.span-4{grid-column:span 4}.card h2,.card h3{line-height:1.2;margin:.1em 0 .55em}.card h2{font-size:1.5rem}.card h3{font-size:1.08rem}.warning{border-left:5px solid var(--red);background:var(--red-soft);padding:15px 17px;border-radius:7px}.notice{border-left:5px solid var(--amber);background:var(--amber-soft);padding:15px 17px;border-radius:7px}.good{border-left:5px solid var(--teal);background:var(--teal-soft);padding:15px 17px;border-radius:7px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metric{border-top:2px solid var(--line);padding-top:9px}.metric b{display:block;color:var(--blue);font-size:1.35rem}.metric small{color:var(--muted)}.tag{display:inline-block;padding:3px 8px;border-radius:999px;background:var(--teal-soft);color:var(--teal);font-weight:800;font-size:.77rem}.tag.fail{background:var(--red-soft);color:var(--red)}.muted,.fine{color:var(--muted)}.fine{font-size:.83rem}.hash,code{font: .87em ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere}.wide{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:.91rem}th,td{text-align:left;vertical-align:top;border-bottom:1px solid var(--line);padding:10px 8px}th{text-transform:uppercase;letter-spacing:.055em;color:#34515b;font-size:.75rem}.num{text-align:right;font-variant-numeric:tabular-nums}.steps{counter-reset:step;list-style:none;padding:0}.steps li{counter-increment:step;position:relative;padding:0 0 20px 48px}.steps li:before{content:counter(step);position:absolute;left:0;top:0;width:31px;height:31px;border-radius:50%;display:grid;place-items:center;background:var(--navy);color:#fff;font-weight:900}.pagehead{padding:42px 0 20px}.pagehead h1{font-size:clamp(2.1rem,5vw,3.5rem)}.pagehead p{max-width:800px;color:var(--muted);font-size:1.05rem}.list{padding-left:1.2rem}.list li{margin:.42em 0}.site-foot{border-top:1px solid var(--line);padding:26px 0;color:var(--muted);font-size:.86rem}.skip{position:absolute;left:-9999px}.skip:focus{left:8px;top:8px;background:white;padding:8px;z-index:10}@media(max-width:800px){.hero-grid{grid-template-columns:1fr}.span-8,.span-7,.span-6,.span-5,.span-4{grid-column:span 12}.metrics{grid-template-columns:repeat(2,1fr)}.nav{align-items:flex-start;flex-direction:column}.shell{width:min(100% - 28px,1100px)}}
"""


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def f(value: float, digits: int = 6) -> str:
    return f"{float(value):.{digits}f}"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def chrome(title: str, active: str, body: str, *, description: str) -> str:
    links = [
        ("index.html", "Overview", "overview"),
        ("results.html", "Results", "results"),
        ("methods.html", "Methods & sources", "methods"),
        ("submission.html", "Submission guide", "submission"),
    ]
    nav_parts = []
    for href, label, key in links:
        current = ' aria-current="page"' if key == active else ""
        nav_parts.append(f'<a href="{href}"{current}>{label}</a>')
    nav = "".join(nav_parts)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="{esc(description)}"><title>{esc(title)} · GEMSDOE50</title><link rel="stylesheet" href="site.css"></head>
<body><a class="skip" href="#main">Skip to content</a><header class="site-head"><div class="shell"><nav class="nav" aria-label="Main navigation"><a class="brand" href="index.html">GEMSDOE50 / H55</a><div class="links">{nav}</div></nav></div></header>
{body}
<footer class="site-foot"><div class="shell"><b>Maximize P(Win) · Own the Outcome</b><br>Research artifact only. No portal upload, organizer score, or weekly slot is represented here. Built from <a href="evidence/results/h55s1-evaluation-20261007.json">machine-readable evidence</a>.</div></footer></body></html>
"""


def load() -> tuple[dict, dict, dict]:
    report = json.loads(REPORT.read_text(encoding="utf-8"))
    unique = json.loads(UNIQUENESS.read_text(encoding="utf-8"))
    zero = report["artifacts"]["recommended_portal_safe_zero_outside"]
    nan = report["artifacts"]["sample_semantics_nan_outside"]
    for artifact in (zero, nan):
        path = ROOT / artifact["path"]
        if not path.is_file() or sha256(path) != artifact["sha256"]:
            raise ValueError(f"artifact drift: {path}")
    if not unique["format"]["all_checks_pass"] or not unique["uniqueness"]["verdict_unique"]:
        raise ValueError("site cannot publish an artifact that failed format/uniqueness")
    return report, unique, {"zero": zero, "nan": nan}


def overview(report: dict, unique: dict, artifacts: dict) -> str:
    zero, nan = artifacts["zero"], artifacts["nan"]
    receipt = json.loads(PRIOR_RECEIPT.read_text(encoding="utf-8"))
    scores = report["holdout"]["method_scores"]
    primary = scores["H55-S1-600m"]["pooled"]
    incumbent = scores["Candidate-B-incumbent"]["pooled"]
    mass = zero["positive_cells"]
    zero_link = esc(zero["path"])
    nan_link = esc(nan["path"])
    body = f"""<main id="main"><section class="hero"><div class="shell"><div class="hero-grid"><div><div class="eyebrow">Unique H55 research TIFF · built 2026-10-07</div><h1>Download the earthquake-geometry artifact.</h1><p>Recurrent relocated-earthquake covariance axes, snapped across-axis to independent LiDAR/radiometric ridges. Single-band competition grid; all values re-read in [0,1]; every prior positive pixel excluded.</p><div class="actions"><a class="download" href="{zero_link}" download>Download portal-safe TIFF · {mass:,} cells</a><a class="download alt" href="{nan_link}" download>NaN-outside twin</a></div><p class="fine" style="color:#d8e7e3">SHA-256 <span class="hash">{esc(zero["sha256"])}</span> · {zero["bytes"]:,} bytes</p></div><aside class="hero-card"><span class="tag fail">Frozen decision</span><strong>NO SLOT</strong><p>This is the requested unique deliverable—not a recommendation. It loses the blocked proxy test to the frozen incumbent. No weekly slot was used.</p><p><a href="results.html">See the falsification evidence →</a></p></aside></div></div></section>
<section class="main"><div class="shell"><div class="grid">
<article class="card span-12"><h2>Executive summary</h2><div class="metrics"><div class="metric"><b>{mass:,}</b><small>binary predicted cells</small></div><div class="metric"><b>{f(primary["score"])}</b><small>H55 pooled local proxy DTI</small></div><div class="metric"><b>{f(incumbent["score"])}</b><small>frozen incumbent, same frame</small></div><div class="metric"><b>{unique["uniqueness"]["n_prior"]}</b><small>unique prior files directly checked</small></div></div><div class="warning" style="margin-top:18px"><b>Do not submit under the frozen rule.</b> H55 loses in all four macrofolds; the 16-subtile candidate-minus-incumbent credit/dot interval is [{f(report["holdout"]["paired_subtile_bootstrap"]["percentile_ci_95"][0])}, {f(report["holdout"]["paired_subtile_bootstrap"]["percentile_ci_95"][1])}]. It also fails matched mass, density, random, uncertainty, inventory-completeness, and ComCat-rights gates.</div></article>
<article class="card span-7"><h2>What is genuinely new</h2><p>The candidate uses the CC BY 4.0 Trugman relocated catalog, not the old smoothed seismicity band. After source/site filters and 90-day/250 m sequence thinning, a normalized triangle test removes Poisson-like background; recurrent local 2-D covariance axes must pass event, year, linearity, length, and bootstrap gates. Placement may move only across each axis toward an independent ridge.</p><p>All {receipt["all_source_assertions"]} prior source assertions were hash-verified: {receipt["unique_sha256"]} byte-distinct TIFFs and {receipt["unique_positive_masks"]} distinct positive masks. Byte-identical copies and finite/NaN semantic twins are explicitly inventoried. A frozen union of every prior positive cell is an output exclusion: final exact overlap is <b>0</b>. Full comparison across {unique["uniqueness"]["n_prior"]} filenames finds no identical candidate hash and maximum 200 m-proximity IoU <b>{f(unique["uniqueness"]["max_iou"])}</b>.</p><p><a href="methods.html">Read methods, source rights, and limitations →</a></p></article>
<aside class="card span-5"><h2>Format facts</h2><ul class="list"><li>one float32 band, EPSG:32611</li><li>3,730 × 3,292 at 100 m</li><li>predictions exactly 0 or 1</li><li>all-finite twin: {zero["finite_cells"]:,} finite cells</li><li>sample twin: NaN only outside footprint</li><li>known-fault exclusion: &gt;300 m</li></ul><div class="good"><b>Range guard passed.</b> The all-finite file re-read with min 0, max 1, and no NaN/Inf—the direct guard against the historical portal range error.</div></aside>
<article class="card span-6"><h2>Why “0.2778” reportedly worked</h2><p>H33-B2 inherited a 40,199-dot owner-reported 0.2708 base and removed 2,545 dots within 200 m of the supplied catalogue. Under the 300 m distance-weighted metric, deleting low-credit dots lowers false-positive cost while preserving hidden-truth maxima. It was efficient pruning, not a new geological detector.</p><p><b>Irregularity:</b> GEMSDOE32 labels those exact bytes <code>UNSCORED</code> and projects 0.274673. No organizer receipt proves the 0.2778 mapping. <a href="results.html#h33">Read the conditional derivation.</a></p></article>
<article class="card span-6"><h2>Can 0.3195 be exceeded?</h2><p>Mathematically yes; empirically not by a validated method here. The repository model says 0.3195 requires about 40.8% weighted coverage at 30,000 dots, or 44.7% at H33-B2's mass. That demands new hidden-fault coverage and substantially better credit per dot—not another blend.</p><p>H55 was a genuinely different detector, but this implementation was falsified. Protecting the slot is part of maximizing P(Win).</p></article>
<article class="card span-12"><h2>Audit trail</h2><p><a href="docs/research/h55-final-analysis.md">Full scientific analysis</a> · <a href="docs/research/h55-hypotheses-preregistered.md">ranked preregistration</a> · <a href="docs/research/h55-protocol-addendum.md">frozen constants</a> · <a href="docs/research/h55-deviation-log.md">three-pass fixes</a> · <a href="evidence/results/h55s1-evaluation-20261007.json">evaluation JSON</a> · <a href="evidence/results/h55s1-full-corpus-check-20261007.json">format/novelty JSON</a></p></article>
</div></div></section></main>"""
    return chrome(
        "Download and executive summary",
        "overview",
        body,
        description="Unique H55 earthquake-geometry TIFF, blocked validation decision, and audit evidence.",
    )


def results_page(report: dict, unique: dict) -> str:
    scores = report["holdout"]["method_scores"]
    order = [
        "H55-S1-300m",
        "H55-S1-600m",
        "H55-S1-1000m",
        "density-1000m",
        "density-2000m",
        "matched-random",
        "Candidate-B-incumbent",
    ]
    rows = "".join(
        f"<tr><td>{esc(name)}</td><td class=num>{f(scores[name]['pooled']['score'])}</td><td class=num>{f(scores[name]['pooled']['credit_per_dot'])}</td><td class=num>{scores[name]['pooled']['prediction_cells']:,}</td></tr>"
        for name in order
    )
    deltas = report["holdout"]["primary_fold_credit_per_dot_delta_vs_incumbent"]
    fold_rows = "".join(
        f"<tr><td>{esc(name)}</td><td class=num>{f(value)}</td><td><span class='tag fail'>lost</span></td></tr>"
        for name, value in deltas.items()
    )
    gates = report["decision"]["numeric_components"]
    gate_rows = "".join(
        f"<tr><td>{esc(name.replace('_', ' '))}</td><td><span class='tag {'good' if passed else 'fail'}'>{'PASS' if passed else 'FAIL'}</span></td></tr>"
        for name, passed in gates.items()
    )
    body = f"""<main id="main"><section class="pagehead"><div class="shell"><div class="eyebrow">Measured, not organizer-scored</div><h1>Results and decision</h1><p>The top-ranked preregistered hypothesis was run once under its frozen gate, corrected for an evaluator bug during review, then rerun with strict prior-pixel exclusion. It did not beat the incumbent.</p></div></section><section class="main"><div class="shell"><div class="grid">
<article class="card span-12"><div class="warning"><b>NO SLOT.</b> Pooled and blocked evidence point in the same direction. No portal upload occurred.</div><h2 style="margin-top:22px">Same-frame SGMC-off proxy</h2><div class="wide"><table><thead><tr><th>method</th><th class=num>DTI</th><th class=num>credit / dot</th><th class=num>dots</th></tr></thead><tbody>{rows}</tbody></table></div><p class="fine">SGMC-off is a necessary local instrument under the project rule, not hidden competition truth. Scores here are not numerically comparable with a leaderboard score.</p></article>
<article class="card span-6"><h2>Four frozen macrofolds</h2><p>Central 600 m H55 minus incumbent, credit per dot:</p><table><thead><tr><th>fold</th><th class=num>delta</th><th>sign</th></tr></thead><tbody>{fold_rows}</tbody></table><p>Paired 16-subtile bootstrap 95% CI: <b>[{f(report["holdout"]["paired_subtile_bootstrap"]["percentile_ci_95"][0])}, {f(report["holdout"]["paired_subtile_bootstrap"]["percentile_ci_95"][1])}]</b>.</p></article>
<article class="card span-6"><h2>Frozen gate</h2><table><tbody>{gate_rows}</tbody></table><p>Scientific gates also fail for validated formal aftershock declustering, complete mine/injection inventory, event-specific relocated covariance, and mixed-network ComCat contributor rights.</p></article>
<article class="card span-12" id="h33"><h2>Why H33-B2 reportedly scored 0.2778</h2><p>The exact artifact has 37,654 binary cells. GEMSDOE32 says it began with a 40,199-cell, owner-reported 0.2708 base and deleted all 2,545 cells at catalogue distance ≤2 pixels. For official triangular kernel <code>k(d)=max(1-d/300m,0)</code>, weighted Tversky is <code>T/[0.2T+0.2F+0.8G]</code>. A no-credit dot adds false-positive cost; deleting one lowers the denominator without lowering <code>T</code>. Catalogue-near predictions are especially suspect because the target is faults omitted from the supplied catalogue.</p><p>That explains the plausible mechanism—sparse support and low-value pruning—but not the score attribution. The sibling audit calls the file <code>UNSCORED</code> and projects 0.274673. No organizer ID/hash crosswalk was found.</p><div class="wide"><table><thead><tr><th>conditional model case</th><th class=num>dots</th><th class=num>DTI</th><th class=num>required credit</th><th class=num>coverage</th><th class=num>credit/dot</th></tr></thead><tbody><tr><td>reported H33-B2</td><td class=num>37,654</td><td class=num>0.2778</td><td class=num>4,759</td><td class=num>38.9%</td><td class=num>0.1264</td></tr><tr><td>0.3195 at compact mass</td><td class=num>30,000</td><td class=num>0.3195</td><td class=num>4,982</td><td class=num>40.8%</td><td class=num>0.1661</td></tr><tr><td>0.3195 at H33 mass</td><td class=num>37,654</td><td class=num>0.3195</td><td class=num>5,465</td><td class=num>44.7%</td><td class=num>0.1451</td></tr></tbody></table></div><p class="fine">Model uses G≈12,226 and matched-mass ratio 1.188. These are calibrated assumptions, not organizer disclosures. <a href="docs/research/h55-final-analysis.md">Full derivation and limits →</a></p></article>
<article class="card span-6"><h2>Novelty</h2><ul class="list"><li>{unique["uniqueness"]["n_prior"]} unique filenames compared directly</li><li>0 exact prior-positive pixels by construction</li><li>max 200 m-proximity IoU {f(unique["uniqueness"]["max_iou"])}</li><li>closest file: <code>{esc(unique["uniqueness"]["worst_overlap_file"])}</code></li><li>identical hashes: 0</li></ul></article>
<article class="card span-6"><h2>Interpretation</h2><p>Broader corridors recover more SGMC credit, but even 1,000 m remains below density and far below Candidate B. The axes are too selective and too weakly tied to mapped surface traces; ridge snapping does not repair that mismatch. This falsifies slot readiness, not every possible use of seismic geometry.</p></article>
</div></div></section></main>"""
    return chrome(
        "Results",
        "results",
        body,
        description="H55 blocked validation, controls, H33 explanation, and no-slot decision.",
    )


def methods_page(report: dict) -> str:
    cat = report["catalog_processing"]
    back = report["background_test"]
    axes = report["axis_fit"]
    body = f"""<main id="main"><section class="pagehead"><div class="shell"><div class="eyebrow">Preregistered research</div><h1>Methods, sources, and limits</h1><p>Earthquake locations generate candidate geometry; density is only a matched control. Exact constants were frozen before fault-proxy scoring.</p></div></section><section class="main"><div class="shell"><div class="grid">
<article class="card span-8"><h2>H55-S1 pipeline</h2><ol class="steps"><li><b>Verify and filter.</b> Check the Zenodo MD5 and schema; require relocated events, depth 0–25 km, and finite template cells; apply 2 km GDR-hot and 3 km explicit anthropogenic-event screens.</li><li><b>Space-time thin.</b> Keep one largest-magnitude event per 250 m UTM cell per 90-day Unix-epoch window, with event-ID tie break.</li><li><b>Test point geometry.</b> Normalize nearest-neighbor triangle area by squared distance to the 20th neighbor; compare with 32 uniform-footprint catalogues and keep empirical p≤0.20.</li><li><b>Fit local axes.</b> Full 2-D covariance in 5 km neighborhoods; require ≥10 events, ≥3 years, linearity ≥0.60, length ≥1.5 km, and 24-bootstrap p90 strike error ≤30°.</li><li><b>Snap independently.</b> Dynamic programming moves only cross-axis toward a 70% 3DEP scarp / 30% radiometric-gradient ridge, with orientation and continuity terms.</li><li><b>Broaden and emit.</b> Test 300/600/1,000 m half-widths, exclude supplied faults by 300 m and all prior positive pixels, then pack binary cells at 3-pixel spacing.</li><li><b>Falsify.</b> Compare with 1/2 km density, novelty-domain random, four translations, Candidate B, four macrofolds, and 16-subtile bootstrap.</li></ol></article>
<aside class="card span-4"><h2>Measured flow</h2><ul class="list"><li>{cat["source_rows"]:,} source events</li><li>{cat["events_after_site_screens"]:,} after geometry/site filters</li><li>{cat["sequence_thinning"]["events_out"]:,} after sequence thinning</li><li>{back["events_kept"]:,} after background test</li><li>{axes["accepted_segments"]:,} accepted axes</li><li>{axes["seed_cells"]:,} occupied fit-seed cells</li></ul><div class="notice"><b>Unverified adaptation.</b> The normalized 2-D triangle test is not the published Ouillon/Sornette 3-D tetrahedron method and is not ACLUD.</div></aside>
<article class="card span-12"><h2>Auditable source table</h2><div class="wide"><table><thead><tr><th>source</th><th>use</th><th>rights / eligibility</th><th>link</th></tr></thead><tbody>
<tr><td>DrivenData DOE GEMS problem/rules</td><td>metric, grid, external-data and TIFF contract</td><td>competition terms; verify before upload</td><td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/">official problem</a></td></tr>
<tr><td>Trugman Nevada relocated catalog</td><td><b>prediction geometry</b></td><td>CC BY 4.0; attributable, adaptable, commercially reusable/shareable</td><td><a href="https://zenodo.org/records/11167510">Zenodo 11167510</a> · <a href="registry/nvreloc_catalog_receipt.json">receipt</a></td></tr>
<tr><td>USGS 3DEP descriptors</td><td>independent topographic ridge</td><td>U.S. public domain; inherited derived raster</td><td><a href="https://www.usgs.gov/3d-elevation-program">3DEP</a></td></tr>
<tr><td>USGS airborne K/Th/U/TC</td><td>independent radiometric ridge</td><td>U.S. public domain; inherited derived raster</td><td><a href="https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits">USGS credits</a></td></tr>
<tr><td>GDR 1391 hot features</td><td>geothermal-operation exclusion proxy</td><td>CC BY 4.0; incomplete inventory</td><td><a href="https://gdr.openei.org/submissions/1391">GDR 1391</a></td></tr>
<tr><td>USGS FDSN/ComCat mixed-network export</td><td>explicit blast/mine/quarry exclusion only</td><td><b>unresolved contributor-specific redistribution</b>; eligibility blocker</td><td><a href="https://earthquake.usgs.gov/fdsnws/event/1/">FDSN service</a></td></tr>
<tr><td>USGS SGMC</td><td>off-catalogue validation only</td><td>U.S. public domain; not prediction input</td><td><a href="https://ngmdb.usgs.gov/Prodesc/proddesc_99016.htm">SGMC</a></td></tr>
</tbody></table></div><p class="fine">Catalog attribution: Trugman, D. T. (2024), <i>Relocated Earthquake Catalog for Nevada (2008–2023)</i>, Zenodo v2, DOI 10.5281/zenodo.11167510, CC BY 4.0. Changes: projection, filtering, site screening, thinning, derived point geometry, axis/ridge/corridor rasterization.</p></article>
<article class="card span-6"><h2>Scientific limitations</h2><ul class="list"><li>250 m/90-day thinning is not validated formal aftershock declustering.</li><li>No event-specific relocated covariance; widths are assumptions.</li><li>Mine/injection inventory is incomplete and not date-matched.</li><li>Epicentre axes can reflect dipping structures, swarms, induced activity, or network artifacts.</li><li>SGMC is incomplete proxy truth, not hidden labels.</li><li>A lineation is not proof of a surface fault or geothermal resource.</li></ul></article>
<article class="card span-6"><h2>Protocol integrity</h2><p>Five hypotheses and falsification gates were committed before H55 scoring. Pass 2 found a split-realization bug, fixed it, and reran everything. Prior-pixel exclusion was added as a restrictive, label-blind novelty hardening and logged as a deviation.</p><p><a href="docs/research/h55-hypotheses-preregistered.md">Preregistration</a> · <a href="docs/research/h55-protocol-addendum.md">constants</a> · <a href="docs/research/h55-deviation-log.md">deviation log</a></p></article>
</div></div></section></main>"""
    return chrome(
        "Methods and sources",
        "methods",
        body,
        description="H55 earthquake-geometry protocol, source licenses, and scientific limitations.",
    )


def submission_page(report: dict, artifacts: dict) -> str:
    zero, nan = artifacts["zero"], artifacts["nan"]
    note = report["artifacts"]["short_submission_note"]
    artifact_name = (
        "GEMSDOE50-H55-SEISGEOM-RIDGESNAP-"
        f"{zero['positive_cells']}-{report['artifacts']['positive_mask_sha256'][:8].upper()}"
    )
    body = f"""<main id="main"><section class="pagehead"><div class="shell"><div class="eyebrow">Manual guide · no automated upload</div><h1>Submission guide</h1><p>The artifact is easy to download and technically valid. The frozen evidence says not to spend a slot on it.</p></div></section><section class="main"><div class="shell"><div class="grid">
<article class="card span-12"><div class="warning"><b>Current decision: NO SLOT.</b> Use this page for audit or only after an explicit owner override. There is no portal receipt and no organizer score.</div></article>
<article class="card span-7"><h2>If the owner overrides the gate</h2><ol class="steps"><li><b>Download unchanged.</b> <a href="{esc(zero["path"])}" download>All-finite portal-safe TIFF</a> (recommended for the historical range parser) or <a href="{esc(nan["path"])}" download>NaN-outside twin</a> (sample semantics).</li><li><b>Verify SHA-256.</b> All-finite: <code>{esc(zero["sha256"])}</code>. NaN twin: <code>{esc(nan["sha256"])}</code>.</li><li><b>Check current rules manually.</b> Sign in at <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">DrivenData</a>; confirm deadline, remaining weekly slots, external-data disclosures, and AI disclosure. Do not rely on this dated page for live status.</li><li><b>Upload one TIFF.</b> Do not re-save, reproject, rename bands, or alter nodata metadata.</li><li><b>Record the receipt.</b> Preserve submission ID, exact file hash, timestamp, portal response, and any returned error/score before making a score claim.</li></ol></article>
<aside class="card span-5"><h2>Name and optional note</h2><p><b>Unique name</b><br><code>{artifact_name}</code></p><p><b>Short note</b><br><q>{esc(note)}</q></p><p class="fine">The note deliberately says the 35,000-cell target was not reached.</p></aside>
<article class="card span-6"><h2>All-finite twin</h2><p><a class="download" href="{esc(zero["path"])}" download>Download {esc(Path(zero["path"]).name)}</a></p><ul class="list"><li>{zero["bytes"]:,} bytes</li><li>{zero["positive_cells"]:,} positive cells</li><li>finite min/max {zero["finite_min"]:.0f}/{zero["finite_max"]:.0f}</li><li>non-finite cells {zero["nonfinite_cells"]}</li><li>nodata {esc(zero["nodata"])}</li></ul><p class="fine">Direct guard against <code>Predicted values must be in range [0, 1]</code>.</p></article>
<article class="card span-6"><h2>NaN-outside twin</h2><p><a class="download" href="{esc(nan["path"])}" download>Download {esc(Path(nan["path"]).name)}</a></p><ul class="list"><li>{nan["bytes"]:,} bytes</li><li>{nan["positive_cells"]:,} positive cells</li><li>finite values only 0/1</li><li>NaN only outside official footprint</li><li>local published-format checker PASS</li></ul><p class="fine">No receipt establishes which twin the current portal prefers; that irregularity is disclosed rather than guessed away.</p></article>
<article class="card span-12"><h2>Required disclosure/access</h2><ul class="list"><li>Manual DrivenData account access and an available weekly feedback slot.</li><li>External-data attribution for Trugman (2024), Zenodo 11167510, CC BY 4.0.</li><li>Disclosure of 3DEP/radiometric/GDR inputs and the unresolved mixed-network ComCat exclusion mask.</li><li>AI-assistance disclosure as required by the current NLR/DOE rules.</li><li>Reproducible repository commit, environment, source receipts, and exact artifact hash.</li></ul></article>
</div></div></section></main>"""
    return chrome(
        "Submission guide",
        "submission",
        body,
        description="Manual H55 TIFF submission checklist, hashes, note, and no-slot warning.",
    )


def main() -> None:
    report, unique, artifacts = load()
    pages = {
        "index.html": overview(report, unique, artifacts),
        "results.html": results_page(report, unique),
        "methods.html": methods_page(report),
        "submission.html": submission_page(report, artifacts),
        "site.css": CSS,
    }
    for name, content in pages.items():
        path = ROOT / name
        path.write_text(content.rstrip() + "\n", encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)} ({path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
