#!/usr/bin/env python3
"""Generate root research pages from committed H55/H56 evidence and H53-A audit records."""

from __future__ import annotations

import hashlib
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "evidence/results/h55s1-evaluation-20261007.json"
UNIQUENESS = ROOT / "evidence/results/h55s1-full-corpus-check-20261007.json"
PRIOR_RECEIPT = ROOT / "evidence/results/h55-prior-corpus-receipt-20261007.json"
H54_SHIP = ROOT / "evidence/h54_ship.json"
H54_VALIDATION = ROOT / "evidence/h54_validation.json"
H53A_VALIDATION = ROOT / "evidence/h53-validation-20261007.json"

CSS = """/* Generated by scripts/build_h55_site.py */
:root{--ink:#17252b;--muted:#52666d;--paper:#f4f1e8;--card:#fffef9;--line:#cdd9d5;--navy:#102f3a;--teal:#00695d;--teal-soft:#dcefe9;--amber:#a45b12;--amber-soft:#fff0d8;--red:#8d2f2a;--red-soft:#f9e5df;--blue:#164b66;--shadow:0 14px 38px rgba(16,47,58,.08)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.62 system-ui,-apple-system,"Segoe UI",sans-serif}a{color:#00606b;text-underline-offset:3px}.shell{width:min(1100px,calc(100% - 40px));margin:auto}.site-head{background:var(--navy);color:white;border-bottom:4px solid #d0934d}.nav{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:17px 0}.brand{color:#fff;text-decoration:none;font-weight:850;letter-spacing:.04em}.links{display:flex;gap:18px;flex-wrap:wrap}.links a{color:#d7e9e5;font-size:.92rem}.hero{background:var(--navy);color:white;padding:52px 0 58px}.hero-grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(270px,.65fr);gap:28px;align-items:center}.eyebrow{text-transform:uppercase;letter-spacing:.14em;font-weight:850;font-size:.74rem;color:#cc9a63}.hero h1,.pagehead h1{letter-spacing:-.035em;line-height:1.04;margin:.18em 0 .35em}.hero h1{font-size:clamp(2.4rem,6vw,4.4rem);max-width:820px}.hero p{color:#d8e7e3;font-size:1.08rem;max-width:760px}.download{display:inline-flex;align-items:center;justify-content:center;background:#e0a25b;color:#15272c;text-decoration:none;font-weight:900;padding:14px 18px;border-radius:9px;box-shadow:0 7px 18px rgba(0,0,0,.18)}.download:hover{background:#efb873}.download.alt{background:transparent;color:white;border:1px solid #88a39d;box-shadow:none}.actions{display:flex;flex-wrap:wrap;gap:11px;margin-top:25px}.hero-card{background:#fdf9ed;color:var(--ink);padding:21px;border-radius:13px;border:1px solid #dbc7a4}.hero-card strong{display:block;font-size:1.45rem;color:var(--red)}.hero-card p{color:var(--ink);font-size:.95rem;margin:.5em 0 0}.main{padding:34px 0 72px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:18px}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:22px;box-shadow:var(--shadow)}.span-12{grid-column:span 12}.span-8{grid-column:span 8}.span-7{grid-column:span 7}.span-6{grid-column:span 6}.span-5{grid-column:span 5}.span-4{grid-column:span 4}.card h2,.card h3{line-height:1.2;margin:.1em 0 .55em}.card h2{font-size:1.5rem}.card h3{font-size:1.08rem}.warning{border-left:5px solid var(--red);background:var(--red-soft);padding:15px 17px;border-radius:7px}.notice{border-left:5px solid var(--amber);background:var(--amber-soft);padding:15px 17px;border-radius:7px}.good{border-left:5px solid var(--teal);background:var(--teal-soft);padding:15px 17px;border-radius:7px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metric{border-top:2px solid var(--line);padding-top:9px}.metric b{display:block;color:var(--blue);font-size:1.35rem}.metric small{color:var(--muted)}.tag{display:inline-block;padding:3px 8px;border-radius:999px;background:var(--teal-soft);color:var(--teal);font-weight:800;font-size:.77rem}.tag.fail{background:var(--red-soft);color:var(--red)}.muted,.fine{color:var(--muted)}.fine{font-size:.83rem}.hash,code{font: .87em ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere}.wide{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:.91rem}th,td{text-align:left;vertical-align:top;border-bottom:1px solid var(--line);padding:10px 8px}th{text-transform:uppercase;letter-spacing:.055em;color:#34515b;font-size:.75rem}.num{text-align:right;font-variant-numeric:tabular-nums}.steps{counter-reset:step;list-style:none;padding:0}.steps li{counter-increment:step;position:relative;padding:0 0 20px 48px}.steps li:before{content:counter(step);position:absolute;left:0;top:0;width:31px;height:31px;border-radius:50%;display:grid;place-items:center;background:var(--navy);color:#fff;font-weight:900}.pagehead{padding:42px 0 20px}.pagehead h1{font-size:clamp(2.1rem,5vw,3.5rem)}.pagehead p{max-width:800px;color:var(--muted);font-size:1.05rem}.list{padding-left:1.2rem}.list li{margin:.42em 0}.site-foot{border-top:1px solid var(--line);padding:26px 0;color:var(--muted);font-size:.86rem}.skip{position:absolute;left:-9999px}.skip:focus{left:8px;top:8px;background:white;padding:8px;z-index:10}@media(max-width:800px){.hero-grid{grid-template-columns:1fr}.span-8,.span-7,.span-6,.span-5,.span-4{grid-column:span 12}.metrics{grid-template-columns:repeat(2,1fr)}.nav{align-items:flex-start;flex-direction:column}.shell{width:min(100% - 28px,1100px)}}
"""


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def f(value: float, digits: int = 6) -> str:
    return f"{float(value):.{digits}f}"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def chrome(title: str, active: str, body: str, *, description: str) -> str:
    links = [
        ("index.html", "Overview", "overview"),
        ("results.html", "Results", "results"),
        ("methods.html", "Methods & sources", "methods"),
        ("submission.html", "Submission guide", "submission"),
    ]
    nav_parts = []
    for href, label, key in links:
        current = ' aria-current="page"' if key == active else ""
        nav_parts.append(f'<a href="{href}"{current}>{label}</a>')
    nav = "".join(nav_parts)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="{esc(description)}"><title>{esc(title)} · GEMSDOE50</title><link rel="stylesheet" href="site.css"></head>
<body><a class="skip" href="#main">Skip to content</a><header class="site-head"><div class="shell"><nav class="nav" aria-label="Main navigation"><a class="brand" href="index.html">GEMSDOE50 / Research</a><div class="links">{nav}</div></nav></div></header>
{body}
<footer class="site-foot"><div class="shell"><b>Maximize P(Win) · Own the Outcome</b><br>Research artifact only. No portal upload, organizer score, or weekly slot is represented here. Built from <a href="evidence/results/h55s1-evaluation-20261007.json">machine-readable evidence</a>.</div></footer></body></html>
"""


def load() -> tuple[dict, dict, dict]:
    report = json.loads(REPORT.read_text(encoding="utf-8"))
    unique = json.loads(UNIQUENESS.read_text(encoding="utf-8"))
    zero = report["artifacts"]["recommended_portal_safe_zero_outside"]
    nan = report["artifacts"]["sample_semantics_nan_outside"]
    for artifact in (zero, nan):
        path = ROOT / artifact["path"]
        if not path.is_file() or sha256(path) != artifact["sha256"]:
            raise ValueError(f"artifact drift: {path}")
    if not unique["format"]["all_checks_pass"] or not unique["uniqueness"]["verdict_unique"]:
        raise ValueError("site cannot publish an artifact that failed format/uniqueness")
    return report, unique, {"zero": zero, "nan": nan}


def load_h54() -> dict:
    ship = json.loads(H54_SHIP.read_text(encoding="utf-8"))
    validation = json.loads(H54_VALIDATION.read_text(encoding="utf-8"))
    for key in ("primary_nan", "all_finite_zeros_twin"):
        artifact = ship["outputs"][key]
        path = ROOT / artifact["path"]
        if not path.is_file() or sha256(path) != artifact["sha256"]:
            raise ValueError(f"H54 artifact drift: {path}")
    if validation["gate"]["shipped_beats_random_in_every_fold"]:
        raise ValueError("H54 site copy assumes the frozen NO-SLOT result")
    return {"ship": ship, "validation": validation}


# ---------------------------------------------------------------------------
# H52-C historical research artifact: keep its files available for audit only.
# The generated page authorizes no portal name, note, upload, or slot.
# ---------------------------------------------------------------------------
H52C_STEM = "gems50-h52-coincidence8-80000-20261007T032938Z"
H52C_DIR = Path("docs/downloads")
_H52C_CACHE: dict[str, str] | None = None


def h52c_parts() -> dict[str, str]:
    """Build the H52-C cards; return empty strings when the receipts are absent."""
    global _H52C_CACHE
    if _H52C_CACHE is not None:
        return _H52C_CACHE
    empty = {"ov": "", "res": "", "sub": ""}
    build = json.loads((ROOT / "evidence/h52_build_80000.json").read_text()) if (
        ROOT / "evidence/h52_build_80000.json").exists() else None
    if not build or "twin" not in build:
        _H52C_CACHE = empty
        return empty
    validation_path = ROOT / "evidence/h52_validation_80k.json"
    uniqueness_path = ROOT / "evidence/h52_uniqueness.json"
    curve_path = ROOT / "evidence/h52_budget_curve.json"
    validation = json.loads(validation_path.read_text()) if validation_path.exists() else None
    uniqueness = json.loads(uniqueness_path.read_text()) if uniqueness_path.exists() else None
    curve = json.loads(curve_path.read_text()) if curve_path.exists() else None

    nan, zero = build["twin"], build["primary"]
    nan_name = Path(nan["path"]).name
    zero_name = Path(zero["path"]).name
    nan_sha, zero_sha = nan["sha256"], zero["sha256"]

    fold_line = ""
    if validation:
        hold = validation["blocked_holdout"]
        cal = validation["calibration"]
        fold_line = (
            f'<li><b>Calibrated instrument:</b> orders the ten artifacts with owner-recorded scores at '
            f'Spearman {f(cal["spearman_vs_published"], 3)} (p = {f(cal["p_value"], 4)}); '
            f'{hold["folds_positive"]}/{hold["n_folds"]} spatially blocked folds beat a matched-mass random '
            f'control ({", ".join(f"{d:+.4f}" for d in hold["deltas"])}).</li>')
    uniq_line = ""
    if uniqueness:
        u = uniqueness["uniqueness"]
        uniq_line = (
            f'<li><b>Unique:</b> {100 * (1 - u["worst_prior_overlap_within_2px_fraction"]):.0f}% of dots are '
            f'&ge;300 m from every dot of the {u["n_priors_compared"]} prior artifacts compared, and '
            f'{100 * (1 - u["reproduced_from_prior_union_fraction"]):.0f}% are outside the union of all prior '
            f'supports.</li>')

    ov = f"""<article class="card span-12" style="border-left:6px solid #164b66"><h2>Historical H52-C research artifact — no slot ({nan["positive_cells"]:,} dots)</h2>
<p>Archived eight-family coincidence experiment, retained for comparison and audit only; it is not a new candidate or a variant to repackage as H55/H58. The method combined topographic, LiDAR, radiometric, potential-field, geodetic-strain, and seismicity evidence.</p>
<p><a class="download" href="{esc(H52C_DIR.as_posix())}/{esc(nan_name)}" download>Download H52-C audit TIFF</a> <a class="download alt" href="{esc(H52C_DIR.as_posix())}/{esc(zero_name)}" download style="color:#17252b">all-finite audit twin</a></p>
<p class="fine">SHA-256 <span class="hash">{esc(nan_sha)}</span> · {nan["bytes"]:,} bytes · all-finite twin SHA-256 <span class="hash">{esc(zero_sha)}</span><br>
Portal entry name/note: none authorized for this no-slot artifact.</p>
<ul class="list">{fold_line}{uniq_line}<li><b>Budget (conditional historical model):</b> the nested-pair inversion assumes the simplified DTI equation and unverified score-to-file associations; 3 px spacing does not make it exact. The resulting bar = 0.0588 and ten-budget curve are not score arithmetic or forecasts. See <a href="docs/h52-decision.md">docs/h52-decision.md</a> and the <a href="docs/research/h56-diagnosis.md">metric correction</a>.</li>
<li><b>Not organizer-scored and no slot recommended:</b> per-dot proxy quality {f(validation["this_work"]["credit_per_dot"], 4) if validation else "—"} sits below every incumbent-family artifact, and the receipt records an SGMC-family submission scoring below matched random on the hidden labels.</li></ul></article>
"""

    res = ""
    if validation or uniqueness or curve:
        rows = "".join(
            f"<tr><td>{esc(r['name'])}</td><td class=num>{f(r['published'], 4)}</td>"
            f"<td class=num>{f(r['credit_per_dot'], 4)}</td><td class=num>{r['dots']:,}</td></tr>"
            for r in sorted(validation["calibration"]["table"], key=lambda r: -r["credit_per_dot"])
        ) if validation else ""
        budget_rows = "".join(
            f"<tr><td class=num>{row['dots']:,}</td><td class=num>{f(row['instrument_credit_per_dot'], 4)}</td>"
            f"<td class=num>{f(row['instrument_dti'], 4)}</td><td class=num>{f(row['model_T'], 1)}</td>"
            f"<td class=num>{f(row['model_dti'], 4)}</td></tr>"
            for row in curve["curve"]
        ) if curve else ""
        res = f"""<article class="card span-12"><h2>H52-C — calibration, blocked holdout, uniqueness and budget</h2>
<p>The instrument is an independent off-catalogue USGS SGMC derivative scored with the competition's own distance-weighted metric. It reproduces the published ordering of the artifacts that have organizer scores — which licenses it as an ordering device, not as a score predictor.</p>
<div class="wide"><table><thead><tr><th>artifact</th><th class=num>owner-recorded score</th><th class=num>instrument credit / dot</th><th class=num>dots</th></tr></thead><tbody>{rows}</tbody></table></div>
<p><b>H52-C:</b> {f(validation["this_work"]["credit_per_dot"], 4) if validation else "—"} credit per dot over {validation["this_work"]["dots"]:,} dots; blocked holdout {validation["blocked_holdout"]["folds_positive"]}/{validation["blocked_holdout"]["n_folds"]} folds positive against matched-mass random. Format re-read from the written bytes: one float32 band, all values in [0, 1], no nodata sentinel, zero dots on the provided catalogue. Uniqueness: worst prior covers {100 * uniqueness["uniqueness"]["worst_prior_overlap_within_2px_fraction"]:.1f}% of dots within 2 px, so {100 * uniqueness["uniqueness"]["min_novel_fraction_at_2px"]:.1f}% are &ge;300 m from any prior dot and {100 * (1 - uniqueness["uniqueness"]["reproduced_from_prior_union_fraction"]):.1f}% are outside every prior support (<a href="registry/prior_artifact_sources.tsv">provenance</a>, <a href="evidence/h52_uniqueness.json">receipt</a>).</p>
<div class="wide"><table><thead><tr><th class=num>dots</th><th class=num>instr. credit/dot (measured)</th><th class=num>instr. DTI (measured)</th><th class=num>model T (extrapolated)</th><th class=num>model DTI (extrapolated)</th></tr></thead><tbody>{budget_rows}</tbody></table></div>
<p class="fine">The measured columns improve monotonically with mass; the model peaks only because it caps credit at the total truth mass, so the shipped 80,000 dots sit inside the measured plateau deliberately. Full derivation: <a href="docs/h52-decision.md">docs/h52-decision.md</a> · receipts <a href="evidence/h52_validation_80k.json">validation</a>, <a href="evidence/h52_budget_curve.json">budget curve</a>.</p></article>
"""

    sub = f"""<article class="card span-12"><h2>Historical H52-C research files — no slot</h2>
<p>H52-C is retained as an audit record, not a submission option. It was below the incumbent family on the local instrument and has no organizer score. <b>Do not upload, relabel, or reuse it as a new candidate.</b></p>
<p><a href="{esc(H52C_DIR.as_posix())}/{esc(nan_name)}" download>NaN-outside audit TIFF</a> (SHA-256 <code>{esc(nan_sha)}</code>) · <a href="{esc(H52C_DIR.as_posix())}/{esc(zero_name)}" download>all-finite audit twin</a> (SHA-256 <code>{esc(zero_sha)}</code>).</p>
<p>Portal entry name/note: none authorized. Decision record: <a href="docs/h52-decision.md">docs/h52-decision.md</a> and <a href="evidence/h52_validation_80k.json">validation evidence</a>.</p></article>
"""

    _H52C_CACHE = {"ov": ov, "res": res, "sub": sub}
    return _H52C_CACHE


def overview(report: dict, unique: dict, artifacts: dict) -> str:
    zero, nan = artifacts["zero"], artifacts["nan"]
    receipt = json.loads(PRIOR_RECEIPT.read_text(encoding="utf-8"))
    scores = report["holdout"]["method_scores"]
    primary = scores["H55-S1-600m"]["pooled"]
    incumbent = scores["Candidate-B-incumbent"]["pooled"]
    mass = zero["positive_cells"]
    zero_link = esc(zero["path"])
    nan_link = esc(nan["path"])
    h52c_ov = h52c_parts()["ov"]
    body = h56_band(load_h56()) + f"""<main id="main"><section class="hero"><div class="shell"><div class="hero-grid"><div><div class="eyebrow">Historical H55-S1 research TIFF · built 2026-10-07 · NO SLOT</div><h1>H55-S1 failed its frozen gate; archive only.</h1><p>Recurrent relocated-earthquake covariance axes, snapped across-axis to independent LiDAR/radiometric ridges. This historical single-band research artifact remains available for audit; it is not a submission recommendation.</p><div class="actions"><a class="download" href="{zero_link}" download>Download H55 audit TIFF · {mass:,} cells</a><a class="download alt" href="{nan_link}" download>NaN-outside audit twin</a></div><p class="fine" style="color:#d8e7e3">SHA-256 <span class="hash">{esc(zero["sha256"])}</span> · {zero["bytes"]:,} bytes</p></div><aside class="hero-card"><span class="tag fail">Frozen decision</span><strong>NO SLOT</strong><p>Historical H55 audit artifact only—not an eligible candidate or submission recommendation. It loses the blocked proxy test to the frozen incumbent. No weekly slot was used.</p><p><a href="results.html">See the falsification evidence →</a></p></aside></div></div></section>
<section class="main"><div class="shell"><div class="grid">
<article class="card span-12"><h2>Executive summary</h2><div class="metrics"><div class="metric"><b>{mass:,}</b><small>binary predicted cells</small></div><div class="metric"><b>{f(primary["score"])}</b><small>H55 pooled local proxy DTI</small></div><div class="metric"><b>{f(incumbent["score"])}</b><small>frozen incumbent, same frame</small></div><div class="metric"><b>{unique["uniqueness"]["n_prior"]}</b><small>unique prior files directly checked</small></div></div><div class="warning" style="margin-top:18px"><b>Do not submit under the frozen rule.</b> H55 loses in all four macrofolds; the 16-subtile candidate-minus-incumbent credit/dot interval is [{f(report["holdout"]["paired_subtile_bootstrap"]["percentile_ci_95"][0])}, {f(report["holdout"]["paired_subtile_bootstrap"]["percentile_ci_95"][1])}]. It also fails matched mass, density, random, uncertainty, inventory-completeness, and ComCat-rights gates.</div></article>
{h52c_ov}
<article class="card span-7"><h2>What is genuinely new</h2><p>The candidate uses the CC BY 4.0 Trugman relocated catalog, not the old smoothed seismicity band. After source/site filters and 90-day/250 m sequence thinning, a normalized triangle test removes Poisson-like background; recurrent local 2-D covariance axes must pass event, year, linearity, length, and bootstrap gates. Placement may move only across each axis toward an independent ridge.</p><p>All {receipt["all_source_assertions"]} prior source assertions were hash-verified: {receipt["unique_sha256"]} byte-distinct TIFFs and {receipt["unique_positive_masks"]} distinct positive masks. Byte-identical copies and finite/NaN semantic twins are explicitly inventoried. A frozen union of every prior positive cell is an output exclusion: final exact overlap is <b>0</b>. Full comparison across {unique["uniqueness"]["n_prior"]} filenames finds no identical candidate hash and maximum 200 m-proximity IoU <b>{f(unique["uniqueness"]["max_iou"])}</b>.</p><p><a href="methods.html">Read methods, source rights, and limitations →</a></p></article>
<aside class="card span-5"><h2>Format facts</h2><ul class="list"><li>one float32 band, EPSG:32611</li><li>3,730 × 3,292 at 100 m</li><li>predictions exactly 0 or 1</li><li>all-finite twin: {zero["finite_cells"]:,} finite cells</li><li>sample twin: NaN only outside footprint</li><li>known-fault exclusion: &gt;300 m</li></ul><div class="good"><b>Range guard passed.</b> The all-finite file re-read with min 0, max 1, and no NaN/Inf—the direct guard against the historical portal range error.</div></aside>
<article class="card span-6"><h2>H33-2-B2 and an unverified 0.2778 association</h2><p>GEMSDOE32's pinned audit describes a 40,199-dot base with 2,545 dots within 200 m of the supplied catalogue removed. If the user-reported 0.2778 belongs to those bytes, metric-efficient pruning is a plausible explanation: unsupported dots can add false-positive cost without improving hidden-truth maxima. The pixels do not prove that cause or any gain in geological recall.</p><p><b>Irregularity:</b> the sibling audit labels those exact bytes <code>UNSCORED</code> and projects 0.274673. No organizer receipt proves a 0.2778 score-to-file mapping. <a href="results.html#h33">Read the conditional derivation</a> and <a href="docs/research/h33-score-review-20261007.md">the full provenance review.</a></p></article>
<article class="card span-6"><h2>The 0.3774 public leader is not a local target score</h2><p>The 2026-10-07 leaderboard snapshot displayed xiaofanhu at 0.3774 (rank 1). H56&rsquo;s legacy 0.386 hidden-DTI number came from a simplified transfer model that has not been recalculated under the exact directional-credit metric; it is not a score forecast or evidence of a result above the public leader. H55 and H53-A failed their own frozen candidate gates; H56 is also NO-GO because its historical TIFF fails the claimed spacing gate and its ComCat rights remain unresolved.</p><p>H55 and H56 remain historical NO-GO / NO SLOT. The current main recommendation is the distinct H59 sharpened topographic-scarp artifact selected by H61; see the start-here band above. This page reports local proxies only, not organizer scores. See <a href="docs/research/h56-diagnosis.md">H56 model caveats</a>, <a href="evidence/emitter-spacing-audit-20261007.json">spacing audit</a>, and <a href="docs/research/h33-score-review-20261007.md">score-provenance review</a>.</p></article>
<article class="card span-12"><h2>Audit trail</h2><p><a href="docs/research/h55-final-analysis.md">Full scientific analysis</a> · <a href="docs/research/h55-hypotheses-preregistered.md">ranked preregistration</a> · <a href="docs/research/h55-protocol-addendum.md">frozen constants</a> · <a href="docs/research/h55-deviation-log.md">three-pass fixes</a> · <a href="evidence/results/h55s1-evaluation-20261007.json">evaluation JSON</a> · <a href="evidence/results/h55s1-full-corpus-check-20261007.json">format/novelty JSON</a></p></article>
</div></div></section></main>"""
    return chrome(
        "Download and executive summary",
        "overview",
        body,
        description="Historical H55/H56 research artifacts, NO-GO decisions, H53-A audit, and score provenance.",
    )


def h53a_archive_block() -> str:
    """Publish this branch's negative H53-A test without promoting its all-zero raster."""
    if not H53A_VALIDATION.is_file():
        return ""
    evidence = json.loads(H53A_VALIDATION.read_text(encoding="utf-8"))
    candidate = evidence["candidate"]
    artifact = candidate["artifact"]
    audit = candidate["lineation_audit_recomputed"]
    incumbent = evidence["frozen_incumbent"]["native_pooled_dti"]["score"]
    ci = evidence["subtile_bootstrap"]["percentile_ci_95"]
    return (
        '<article class="card span-12" id="h53a-no-go"><div class="warning">'
        "<b>H53-A probe/TMI: NO-GO / NO SLOT.</b> This is a distinct experiment from the "
        "repository's earlier H53 TMI-conjunction artifact. Do not upload this all-zero file "
        "or spend a weekly scoring slot.</div>"
        "<p>The preregistered point-pattern detector accepted "
        f"<b>{audit['clusters_accepted']}/{audit['clusters_tested']}</b> clusters and emitted "
        f"<b>{artifact['positive_cells']:,}</b> positive cells. Its local blocked-proxy DTI is "
        f"0.000000 versus {incumbent:.6f} for the frozen comparator; the paired subtile-bootstrap "
        f"95% interval is [{ci[0]:.6f}, {ci[1]:.6f}]. These are local proxy measurements, not "
        "organizer scores or a forecast of hidden-test performance.</p>"
        f'<p><a href="{esc(artifact["path"])}" download>Audit-only H53-A GeoTIFF</a> · '
        f"SHA-256 <code>{esc(artifact['sha256'])}</code>. It is Float32 on the official grid, "
        "with valid-footprint values in [0,1]; every valid value is zero. Source mirror bytes "
        "were not matched to official assets, so competition-use rights/provenance are not cleared.</p>"
        '<p><a href="docs/research/h53-hypotheses-20261007.md">Four ranked hypotheses</a> · '
        '<a href="docs/research/h53-preregistration-20261007.md">frozen protocol</a> · '
        '<a href="docs/research/h33-score-review-20261007.md">H33 score and 0.3774 review</a> · '
        '<a href="evidence/h53-validation-20261007.json">validation evidence</a> · '
        '<a href="docs/pass3-review-20261007.md">three-pass review</a>.</p></article>'
    )


def results_page(report: dict, unique: dict, h54: dict) -> str:
    scores = report["holdout"]["method_scores"]
    h54_ship = h54["ship"]
    h54_primary = h54_ship["outputs"]["primary_nan"]
    order = [
        "H55-S1-300m",
        "H55-S1-600m",
        "H55-S1-1000m",
        "density-1000m",
        "density-2000m",
        "matched-random",
        "Candidate-B-incumbent",
    ]
    rows = "".join(
        f"<tr><td>{esc(name)}</td><td class=num>{f(scores[name]['pooled']['score'])}</td><td class=num>{f(scores[name]['pooled']['credit_per_dot'])}</td><td class=num>{scores[name]['pooled']['prediction_cells']:,}</td></tr>"
        for name in order
    )
    deltas = report["holdout"]["primary_fold_credit_per_dot_delta_vs_incumbent"]
    fold_rows = "".join(
        f"<tr><td>{esc(name)}</td><td class=num>{f(value)}</td><td><span class='tag fail'>lost</span></td></tr>"
        for name, value in deltas.items()
    )
    gates = report["decision"]["numeric_components"]
    gate_rows = "".join(
        f"<tr><td>{esc(name.replace('_', ' '))}</td><td><span class='tag {'good' if passed else 'fail'}'>{'PASS' if passed else 'FAIL'}</span></td></tr>"
        for name, passed in gates.items()
    )
    h52c_res = h52c_parts()["res"]
    body = f"""<main id="main"><section class="pagehead"><div class="shell"><div class="eyebrow">Measured, not organizer-scored</div><h1>Results and decision</h1><p>The top-ranked preregistered hypothesis was run once under its frozen gate, corrected for an evaluator bug during review, then rerun with strict prior-pixel exclusion. It did not beat the incumbent.</p></div></section><section class="main"><div class="shell"><div class="grid">
<article class="card span-12"><div class="warning"><b>NO SLOT.</b> Pooled and blocked evidence point in the same direction. No portal upload occurred.</div><h2 style="margin-top:22px">Same-frame SGMC-off proxy</h2><div class="wide"><table><thead><tr><th>method</th><th class=num>DTI</th><th class=num>credit / dot</th><th class=num>dots</th></tr></thead><tbody>{rows}</tbody></table></div><p class="fine">SGMC-off is a necessary local instrument under the project rule, not hidden competition truth. Scores here are not numerically comparable with a leaderboard score.</p></article>
<article class="card span-6"><h2>Four frozen macrofolds</h2><p>Central 600 m H55 minus incumbent, credit per dot:</p><table><thead><tr><th>fold</th><th class=num>delta</th><th>sign</th></tr></thead><tbody>{fold_rows}</tbody></table><p>Paired 16-subtile bootstrap 95% CI: <b>[{f(report["holdout"]["paired_subtile_bootstrap"]["percentile_ci_95"][0])}, {f(report["holdout"]["paired_subtile_bootstrap"]["percentile_ci_95"][1])}]</b>.</p></article>
<article class="card span-6"><h2>Frozen gate</h2><table><tbody>{gate_rows}</tbody></table><p>Scientific gates also fail for validated formal aftershock declustering, complete mine/injection inventory, event-specific relocated covariance, and mixed-network ComCat contributor rights.</p></article>
<article class="card span-12" id="h33"><h2>H33-B2 and the unverified 0.2778 association</h2><p>The exact artifact has 37,654 binary cells. GEMSDOE32 says it began with a 40,199-cell, owner-reported 0.2708 base and deleted all 2,545 cells at catalogue distance ≤2 pixels. For official triangular kernel <code>k(d)=max(1-d/300m,0)</code>, weighted Tversky is <code>T/[0.2T+0.2F+0.8G]</code>. A no-credit dot adds false-positive cost; deleting one lowers the denominator without lowering <code>T</code>. Catalogue-near predictions are especially suspect because the target is faults omitted from the supplied catalogue.</p><p>That makes metric-efficient pruning a plausible mechanism, not a verified cause. The sibling audit calls the file <code>UNSCORED</code> and projects 0.274673; no organizer receipt or score-to-hash crosswalk was found. The public leaderboard snapshot (2026-10-07) displayed xiaofanhu at 0.3774 (rank 1) and extradr19 at 0.2778 (rank 13), but supplies no TIFF/hash crosswalk to the local artifacts. The 0.3195 rows below are an older conditional model scenario; for caveats, see <a href="docs/research/h56-diagnosis.md">H56 diagnosis</a> and <a href="docs/research/h33-score-review-20261007.md">the H33/H53-A review</a>.</p><div class="wide"><table><thead><tr><th>conditional model case</th><th class=num>dots</th><th class=num>DTI</th><th class=num>required credit</th><th class=num>coverage</th><th class=num>credit/dot</th></tr></thead><tbody><tr><td>reported H33-B2</td><td class=num>37,654</td><td class=num>0.2778</td><td class=num>4,759</td><td class=num>38.9%</td><td class=num>0.1264</td></tr><tr><td>0.3195 at compact mass</td><td class=num>30,000</td><td class=num>0.3195</td><td class=num>4,982</td><td class=num>40.8%</td><td class=num>0.1661</td></tr><tr><td>0.3195 at H33 mass</td><td class=num>37,654</td><td class=num>0.3195</td><td class=num>5,465</td><td class=num>44.7%</td><td class=num>0.1451</td></tr></tbody></table></div><p class="fine">Legacy table uses G≈12,226 and matched-mass ratio 1.188 under the simplified DTI=T/(0.2N+0.8G) model, which assumes truth-side and prediction-side matched credit are equal. A 3 px spacing rule does not establish that condition; these values are conditional arithmetic, not an exact score inversion or organizer disclosure. <a href="docs/research/h33-02778-study-20261007.md">Metric-algebra correction and provenance limits</a> · <a href="docs/research/h55-final-analysis.md">Full derivation and limits →</a></p></article>
{h53a_archive_block()}
<article class="card span-6"><h2>Novelty</h2><ul class="list"><li>{unique["uniqueness"]["n_prior"]} unique filenames compared directly</li><li>0 exact prior-positive pixels by construction</li><li>max 200 m-proximity IoU {f(unique["uniqueness"]["max_iou"])}</li><li>closest file: <code>{esc(unique["uniqueness"]["worst_overlap_file"])}</code></li><li>identical hashes: 0</li></ul></article>
<article class="card span-6"><h2>Interpretation</h2><p>Broader corridors recover more SGMC credit, but even 1,000 m remains below density and far below Candidate B. The axes are too selective and too weakly tied to mapped surface traces; ridge snapping does not repair that mismatch. This falsifies slot readiness, not every possible use of seismic geometry.</p></article>
<article class="card span-12"><h2>Latest-main H54 integration</h2><p>H54 is a separate corpus-calibrated field and metric-derived stratified emitter merged from another audited session. Its 40,000-cell artifact is now also in H55's strict prior-positive exclusion corpus. H54 did not beat its matched-mass random control in every frozen block, so it is likewise <b>NO SLOT</b>; its model-implied DTI is not an organizer score.</p><p><a href="{esc(h54_primary["path"])}" download>Download the H54 NaN-outside research TIFF</a> · SHA-256 <code>{esc(h54_primary["sha256"])}</code> · <a href="evidence/h54_validation.json">validation evidence</a> · <a href="evidence/h54_ship.json">build receipt</a></p><p class="fine">Audited comparison-only H51 consensus twins: <a href="docs/downloads/gemsdoe50-h51-corridor-consensus-mix-20261007T0200Z.tif">NaN-outside</a> · <a href="docs/downloads/gemsdoe50-h51-corridor-consensus-mix-20261007T0200Z-allfinite.tif">all-finite</a>. They are prior artifacts, not H55 outputs.</p></article>
{h52c_res}</div></div></section></main>"""
    return chrome(
        "Results",
        "results",
        body + h56_results_block(load_h56()),
        description="H55 blocked validation, H53-A no-go, H33 score caveats, and no-slot decisions.",
    )


def methods_page(report: dict) -> str:
    cat = report["catalog_processing"]
    back = report["background_test"]
    axes = report["axis_fit"]
    body = f"""<main id="main"><section class="pagehead"><div class="shell"><div class="eyebrow">Preregistered research</div><h1>Methods, sources, and limits</h1><p>Earthquake locations generate candidate geometry; density is only a matched control. Exact constants were frozen before fault-proxy scoring.</p></div></section><section class="main"><div class="shell"><div class="grid">
<article class="card span-8"><h2>H55-S1 pipeline</h2><ol class="steps"><li><b>Verify and filter.</b> Check the Zenodo MD5 and schema; require relocated events, depth 0–25 km, and finite template cells; apply 2 km GDR-hot and 3 km explicit anthropogenic-event screens.</li><li><b>Space-time thin.</b> Keep one largest-magnitude event per 250 m UTM cell per 90-day Unix-epoch window, with event-ID tie break.</li><li><b>Test point geometry.</b> Normalize nearest-neighbor triangle area by squared distance to the 20th neighbor; compare with 32 uniform-footprint catalogues and keep empirical p≤0.20.</li><li><b>Fit local axes.</b> Full 2-D covariance in 5 km neighborhoods; require ≥10 events, ≥3 years, linearity ≥0.60, length ≥1.5 km, and 24-bootstrap p90 strike error ≤30°.</li><li><b>Snap independently.</b> Dynamic programming moves only cross-axis toward a 70% 3DEP scarp / 30% radiometric-gradient ridge, with orientation and continuity terms.</li><li><b>Broaden and emit.</b> Test 300/600/1,000 m half-widths, exclude supplied faults by 300 m and all prior positive pixels, then pack binary cells at 3-pixel spacing.</li><li><b>Falsify.</b> Compare with 1/2 km density, novelty-domain random, four translations, Candidate B, four macrofolds, and 16-subtile bootstrap.</li></ol></article>
<aside class="card span-4"><h2>Measured flow</h2><ul class="list"><li>{cat["source_rows"]:,} source events</li><li>{cat["events_after_site_screens"]:,} after geometry/site filters</li><li>{cat["sequence_thinning"]["events_out"]:,} after sequence thinning</li><li>{back["events_kept"]:,} after background test</li><li>{axes["accepted_segments"]:,} accepted axes</li><li>{axes["seed_cells"]:,} occupied fit-seed cells</li></ul><div class="notice"><b>Unverified adaptation.</b> The normalized 2-D triangle test is not the published Ouillon/Sornette 3-D tetrahedron method and is not ACLUD.</div></aside>
<article class="card span-12"><h2>Historical H56 artifact — NO SLOT</h2><p>H56 used five independent USGS 3DEP 1 m LiDAR scarp/terrain descriptors and 1,466 declustered ComCat lineations as corroboration. Its written 90,000-dot TIFF has a 1.0 px minimum nearest-neighbour distance, not the claimed 3.0 px; the shared emitter is corrected for future builds, but the artifact was not rebuilt. H56 is research-only: its ComCat contributor rights and sponsor-sharing status also remain unresolved, and its 0.386 hidden DTI is a transfer-model estimate, not an organizer score.</p><p><a href="docs/research/h56-diagnosis.md">H56 score/transfer analysis</a> · <a href="docs/hypotheses-20261007-h56.md">five ranked hypotheses</a> · <a href="evidence/emitter-spacing-audit-20261007.json">spacing audit</a> · <a href="docs/research/comcat-license-review-20261007.md">ComCat rights review</a>.</p></article>
<article class="card span-12"><h2>Auditable source table</h2><div class="wide"><table><thead><tr><th>source</th><th>use</th><th>rights / eligibility</th><th>link</th></tr></thead><tbody>
<tr><td>DrivenData DOE GEMS problem/rules</td><td>metric, grid, external-data and TIFF contract</td><td>competition terms; verify before upload</td><td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/">official problem</a></td></tr>
<tr><td>Trugman Nevada relocated catalog</td><td><b>prediction geometry</b></td><td>CC BY 4.0; attributable, adaptable, commercially reusable/shareable</td><td><a href="https://zenodo.org/records/11167510">Zenodo 11167510</a> · <a href="registry/nvreloc_catalog_receipt.json">receipt</a></td></tr>
<tr><td>USGS 3DEP descriptors</td><td>independent topographic ridge</td><td>U.S. public domain; inherited derived raster</td><td><a href="https://www.usgs.gov/3d-elevation-program">3DEP</a></td></tr>
<tr><td>USGS airborne K/Th/U/TC</td><td>independent radiometric ridge</td><td>U.S. public domain; inherited derived raster</td><td><a href="https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits">USGS credits</a></td></tr>
<tr><td>GDR 1391 hot features</td><td>geothermal-operation exclusion proxy</td><td>CC BY 4.0; incomplete inventory</td><td><a href="https://gdr.openei.org/submissions/1391">GDR 1391</a></td></tr>
<tr><td>USGS FDSN/ComCat mixed-network export</td><td>H55 anthropogenic-event screen; H56 event-lineation corroboration</td><td><b>unresolved contributor-specific redistribution and sponsor sharing</b>; blocks any H56 upload</td><td><a href="https://earthquake.usgs.gov/fdsnws/event/1/">FDSN service</a> · <a href="docs/research/comcat-license-review-20261007.md">rights review</a></td></tr>
<tr><td>USGS SGMC</td><td>off-catalogue validation only</td><td>U.S. public domain; not prediction input</td><td><a href="https://ngmdb.usgs.gov/Prodesc/proddesc_99016.htm">SGMC</a></td></tr>
</tbody></table></div><p class="fine">Catalog attribution: Trugman, D. T. (2024), <i>Relocated Earthquake Catalog for Nevada (2008–2023)</i>, Zenodo v2, DOI 10.5281/zenodo.11167510, CC BY 4.0. Changes: projection, filtering, site screening, thinning, derived point geometry, axis/ridge/corridor rasterization.</p></article>
<article class="card span-6"><h2>Scientific limitations</h2><ul class="list"><li>250 m/90-day thinning is not validated formal aftershock declustering.</li><li>No event-specific relocated covariance; widths are assumptions.</li><li>Mine/injection inventory is incomplete and not date-matched.</li><li>Epicentre axes can reflect dipping structures, swarms, induced activity, or network artifacts.</li><li>SGMC is incomplete proxy truth, not hidden labels.</li><li>A lineation is not proof of a surface fault or geothermal resource.</li></ul></article>
<article class="card span-6"><h2>Protocol integrity</h2><p>Five hypotheses and falsification gates were committed before H55 scoring. Pass 2 found a split-realization bug, fixed it, and reran everything. Prior-pixel exclusion was added as a restrictive, label-blind novelty hardening and logged as a deviation.</p><p><a href="docs/research/h55-hypotheses-preregistered.md">Preregistration</a> · <a href="docs/research/h55-protocol-addendum.md">constants</a> · <a href="docs/research/h55-deviation-log.md">deviation log</a></p></article>
</div></div></section></main>"""
    return chrome(
        "Methods and sources",
        "methods",
        body,
        description="H56 candidate methods, H55 point-geometry protocol, source rights, and scientific limitations.",
    )


def submission_page(report: dict, artifacts: dict, h54: dict) -> str:
    zero, nan = artifacts["zero"], artifacts["nan"]
    h54_ship = h54["ship"]
    h54_nan = h54_ship["outputs"]["primary_nan"]
    h54_zero = h54_ship["outputs"]["all_finite_zeros_twin"]
    h52c_sub = h52c_parts()["sub"]
    body = f"""<main id="main"><section class="pagehead"><div class="shell"><div class="eyebrow">Submission status and historical archive</div><h1>Submission guide</h1><p>Current main recommendation: the already-built H59 sharpened topographic-scarp file selected by H61. The link, corrected entry name, and note appear in the start-here band below. H55/H56/H57/H58 remain historical NO-GO / NO SLOT; their archived files are not submission options.</p></div></section><section class="main"><div class="shell"><div class="grid">
<article class="card span-12"><div class="warning"><b>Only the H59 file in the H61 start-here band is recommended.</b> The H55/H56/H57/H58 artifacts below are audit records only; do not upload or repackage them, and do not use any historical name or note. No organizer score exists for any local proxy.</div></article>
<article class="card span-7"><h2>H55-S1 historical artifacts — NO SLOT</h2><p>H55 failed its frozen gate and is retained as a research record, not a submission option. The all-finite file (<a href="{esc(zero["path"])}" download>download</a>; SHA-256 <code>{esc(zero["sha256"])}</code>) and NaN-outside twin (<a href="{esc(nan["path"])}" download>download</a>; SHA-256 <code>{esc(nan["sha256"])}</code>) are archive links only.</p><p><b>Do not upload these files.</b> No portal entry name or note is authorized for H55. See the <a href="docs/research/h55-final-analysis.md">frozen H55 decision and analysis</a>.</p></article>
<aside class="card span-5"><h2>No portal name or note</h2><p>H55-S1 did not pass its gate. Do not reuse the historical name, short note, or TIFF as a new submission.</p><p class="fine">The achieved mass and spacing shortfall remain documented in the linked audit record.</p></aside>
<article class="card span-6"><h2>All-finite twin</h2><p><a class="download" href="{esc(zero["path"])}" download>Download {esc(Path(zero["path"]).name)}</a></p><ul class="list"><li>{zero["bytes"]:,} bytes</li><li>{zero["positive_cells"]:,} positive cells</li><li>finite min/max {zero["finite_min"]:.0f}/{zero["finite_max"]:.0f}</li><li>non-finite cells {zero["nonfinite_cells"]}</li><li>nodata {esc(zero["nodata"])}</li></ul><p class="fine">Direct guard against <code>Predicted values must be in range [0, 1]</code>.</p></article>
<article class="card span-6"><h2>NaN-outside twin</h2><p><a class="download" href="{esc(nan["path"])}" download>Download {esc(Path(nan["path"]).name)}</a></p><ul class="list"><li>{nan["bytes"]:,} bytes</li><li>{nan["positive_cells"]:,} positive cells</li><li>finite values only 0/1</li><li>NaN only outside official footprint</li><li>local published-format checker PASS</li></ul><p class="fine">No receipt establishes which twin the current portal prefers; that irregularity is disclosed rather than guessed away.</p></article>
<article class="card span-12"><h2>Integrated H54 artifact — also NO SLOT</h2><p>H54 is retained for audit and is not an alternative slot recommendation. <a href="{esc(h54_nan["path"])}" download>NaN-outside TIFF</a> (SHA-256 <code>{esc(h54_nan["sha256"])}</code>) · <a href="{esc(h54_zero["path"])}" download>all-finite twin</a> (SHA-256 <code>{esc(h54_zero["sha256"])}</code>). See <a href="evidence/h54_validation.json">its failed frozen gate</a>.</p></article>
<article class="card span-12"><h2>Required disclosure/access</h2><ul class="list"><li>Manual DrivenData account access and an available weekly feedback slot.</li><li>External-data attribution for Trugman (2024), Zenodo 11167510, CC BY 4.0.</li><li>Disclosure of 3DEP/radiometric/GDR inputs and the unresolved mixed-network ComCat exclusion mask.</li><li>AI-assistance disclosure as required by the current NLR/DOE rules.</li><li>Reproducible repository commit, environment, source receipts, and exact artifact hash.</li></ul></article>
{h52c_sub}</div></div></section></main>"""
    return chrome(
        "Submission guide",
        "submission",
        h56_band(load_h56()) + body + h56_results_block(load_h56()),
        description="H61 recommends the built H59 sharpened topographic-scarp candidate; historical H55/H56 artifacts are archive-only NO-GO records.",
    )


H56_BUILD = ROOT / "evidence" / "h56_build.json"
H56_CHECK = ROOT / "evidence" / "h56_check_submission.json"
H56_HOLDOUT = ROOT / "evidence" / "h56_holdout_offcat.json"
H56_UNIQ = ROOT / "evidence" / "h56_uniqueness.json"


def load_h56() -> dict | None:
    """Every number in the H56 band comes from a committed evidence file, so the published page
    cannot drift from the measurement.  Returns None when the H56 session's files are absent."""
    if not H56_BUILD.exists():
        return None
    build = json.loads(H56_BUILD.read_text(encoding="utf-8"))
    name, n = build["checks"]["name"], build["checks"]["n_dots"]
    out = {
        "build": build,
        "check": json.loads(H56_CHECK.read_text(encoding="utf-8")) if H56_CHECK.exists() else {},
        "holdout": json.loads(H56_HOLDOUT.read_text(encoding="utf-8")) if H56_HOLDOUT.exists() else {},
        "unique": json.loads(H56_UNIQ.read_text(encoding="utf-8")) if H56_UNIQ.exists() else {},
        "allfinite": f"docs/downloads/{name}-{n}-allfinite.tif",
        "nan": f"docs/downloads/{name}-{n}-nan.tif",
        "zip": f"docs/downloads/{name}-{n}-allfinite.zip",
    }
    return out if (ROOT / out["allfinite"]).is_file() else None


def h56_band(d: dict | None) -> str:
    """Render H56's historical one-click audit band without implying submission eligibility.

    The artifact is retained because its measurements are useful for research comparison, not
    because it is a current candidate. The spacing correction is prospective only; the stored
    TIFF still measures 1.0 px minimum spacing and the ComCat rights gate remains unresolved.
    """
    if not d:
        return ""
    b, chk, hold, uniq = d["build"], d["check"], d["holdout"], d["unique"]
    n = b["checks"]["n_dots"]
    fin = b["checks"]["files"].get(d["allfinite"].split("/")[-1], {})
    fmt = chk.get("format", {})
    u = uniq.get("uniqueness") or chk.get("uniqueness") or {}
    summ = hold.get("summary") or {}
    ci = (hold.get("summary") or {}).get("paired_ci95") or [0.0, 0.0]
    off = b["checks"].get("sgmc_off", {})
    model = b["checks"].get("modelled_hidden", {})
    ms = b["mass_selection"]
    return (
        '<section class="main" id="h56"><div class="shell"><div class="grid">'
        '<article class="card span-12">'
        "<h2>Historical H56 research TIFF — NO SLOT; retained for audit only</h2>"
        '<div class="hero" style="border-radius:10px;padding:18px 20px;margin-bottom:14px">'
        f'<div class="actions"><a class="download" href="{esc(d["allfinite"])}" download>'
        f'Download {esc(d["allfinite"].split("/")[-1])}</a>'
        f'<a class="download alt" href="{esc(d["nan"])}" download>NaN-outside twin</a>'
        f'<a class="download alt" href="{esc(d["zip"])}" download>.zip</a></div>'
        f'<p class="fine" style="color:#d8e7e3">SHA-256 <span class="hash">'
        f'{esc(fin.get("sha256", "n/a"))}</span> &middot; {fin.get("bytes", 0):,} bytes &middot; '
        f"{n:,} predicted cells &middot; historical archive only; no portal name or note is authorized</p>"
        '<p class="fine" style="color:#d8e7e3"><b>Portal name/note:</b> none authorized for this NO-GO.</p></div>'
        '<p class="warning"><b>Research download only; do not submit.</b> The post-run byte audit measured '
        '1.0 px minimum nearest-neighbour spacing in this historical H56 TIFF, not the claimed 3.0 px. '
        'Its ComCat-derived corroboration also retains unresolved contributor-specific sponsor-sharing '
        'rights. See <a href="evidence/emitter-spacing-audit-20261007.json">spacing measurements</a> '
        'and <a href="docs/research/comcat-license-review-20261007.md">rights review</a>.</p>'
        "<p><b>Why this file cannot reproduce the portal error.</b> The portal once rejected an "
        "upload with <code>Predicted values must be in range [0, 1]</code>. A non-finite cell makes "
        "a plain <code>min()/max()</code> validator see <code>NaN</code>, and "
        "<code>NaN &lt;= 1</code> is false. This file writes <b>0.0 outside the study footprint</b>, "
        "so every one of the 12,279,160 cells is finite and inside <code>[0, 1]</code>. The "
        "<code>-nan.tif</code> twin keeps the official sample's convention for portals that "
        "accept it.</p>"
        '<div class="metrics">'
        f'<div class="metric"><b>{f(off.get("dti", 0.0))}</b><small>off-catalogue DTI</small></div>'
        f'<div class="metric"><b>{f(b["checks"].get("lift_over_uniform", 0.0), 3)}x</b>'
        "<small>vs matched-mass uniform</small></div>"
        f'<div class="metric"><b>{summ.get("positive_macrofolds", 0)}/'
        f'{summ.get("n_macrofolds", 4)}</b><small>frozen holdout macrofolds positive</small></div>'
        f'<div class="metric"><b>{f(u.get("max_iou", 0.0))}</b>'
        "<small>worst full-pixel IoU vs priors</small></div></div>"
        "<h3>H56 executive summary</h3>"
        "<p>Use the full published metric for every binary raster: <code>DTI = T / "
        "(T + 0.2(N - M) + 0.8(G - T))</code>, where <code>T=TP_w</code> is truth-side credit and "
        "<code>M</code> is summed prediction-side matched credit. The often-used simplification "
        "<code>T/(0.2N + 0.8G)</code> requires <code>T=M</code>; 3 px dot spacing alone does not "
        "establish it. Dense top-<i>N</i> picks can still saturate truth-side credit while increasing "
        "prediction-side false-positive cost. The legacy H56 transfer-model output was not "
        "recalculated under this clarification and is not a score forecast. The "
        "historical H56 raster used the old block-quantised emitter (measured minimum nearest-neighbour "
        "distance 1 px); the weighted Euclidean Poisson-disk emitter is now corrected for future builds, "
        "but this file was not rebuilt. The candidate used the only evidence family that measured as informative about faults the given "
        "catalogue does not contain (USGS 3DEP 1 m LiDAR scarp descriptors: enrichment "
        "1.21&ndash;1.42, against 1.02&ndash;1.09 for every magnetic and radiometric channel), "
        "corroborated multiplicatively by 1,466 declustered USGS ComCat epicentre lineaments. "
        'Full working: <a href="docs/research/h56-diagnosis.md">h56-diagnosis.md</a> &middot; '
        '<a href="docs/hypotheses-20261007-h56.md">five screened hypotheses</a>.</p>'
        f'<p class="muted">Format gate <code>all_checks_pass={fmt.get("all_checks_pass")}</code>. '
        f'Uniqueness gate: worst full-pixel IoU <b>{f(u.get("max_iou", 0.0))}</b> against every '
        f'prior artifact on disk, minimum novel fraction at 2 px proximity '
        f'{f(u.get("min_novel_fraction_at_2px", 0.0), 3)}, no SHA match. Frozen blocked holdout '
        f"paired block-bootstrap 95% CI [{f(ci[0])}, {f(ci[1])}]. <b>Modelled</b> hidden DTI "
        f'{model.get("dti_modelled", 0.0):.3f} &mdash; a model with a stated transfer assumption '
        f'(factor {ms["transfer_factor"]}, band {ms["transfer_band"]}), '
        "<b>not an organizer score or score forecast</b>. The legacy 0.386 estimate used a "
        "simplified metric reduction that has not been recalculated under the exact TP/FP/FN form. "
        "Do not compare it with the public leaderboard. "
        "No page in this repository claims portal acceptance, because no upload receipt exists. "
        '<a href="docs/research/h33-score-review-20261007.md">Score-provenance caveats</a>.</p>'
        '<p class="warning"><b>NO-GO; do not upload H56.</b> The historical TIFF fails its claimed '
        'Euclidean-spacing gate (1.0 px minimum) and uses mixed-network ComCat-derived geometry whose '
        'contributor-specific challenge-use and sponsor-sharing rights remain unresolved. The 0.386 '
        'hidden-DTI figure is a transfer-model output, not a score.</p>'
        "<h3>Submission checklist withdrawn for H56</h3>"
        '<p><b>Do not upload this historical file.</b> A future rebuild would be a new candidate and '
        'must be separately preregistered and revalidated from the start. This old hash and its '
        'historical label are not authorized for portal use.</p>'
        '<p class="notice"><b>Separate H53-A probe/TMI experiment: NO-GO / NO SLOT.</b> Its all-zero TIFF is audit-only, not this H56 download. <a href="results.html#h53a-no-go">Read the negative result and do not upload it.</a></p>'
        "</article></div></div></section>"
    )


def h56_results_block(d: dict | None) -> str:
    if not d:
        return ""
    b = d["build"]
    rows = "".join(
        "<tr><td>{n:,}</td><td>{dti:.4f}</td><td>{uni:.4f}</td><td>{lift:.2f}x</td>"
        "<td>{cd:.4f}</td><td>{md:.3f}</td></tr>".format(
            n=v["n_dots"], dti=v["sgmc_off"]["dti"], uni=v["sgmc_off_uniform_mean"],
            lift=v["lift_over_uniform"], cd=v["sgmc_off"]["credit_per_dot"],
            md=v["model"]["dti_modelled"])
        for _, v in sorted(b["sweep"].items(), key=lambda kv: kv[1]["n_dots"]))
    fold_rows = "".join(
        "<tr><td>{fold}</td><td>{c:.4f}</td><td>{u:.4f}</td><td>{t}</td><td>{n:,}</td>"
        "<td>{lift:.2f}x</td></tr>".format(
            fold=esc(k), c=v["dti_candidate"], u=v["dti_uniform_mean"],
            t=("&mdash;" if v.get("dti_translation_mean") is None
               else f"{v['dti_translation_mean']:.4f}"),
            n=v["candidate_dots_in_cell"], lift=v["lift_over_uniform"])
        for k, v in (d["holdout"].get("folds") or {}).items())
    return (
        '<main><section class="main"><div class="shell"><div class="grid">'
        '<article class="card span-12"><h2>Historical H56 mass sweep and calibrated proxy transfer</h2>'
        '<p class="warning"><b>Research-only, not a submission recommendation.</b> These are offline proxy measurements; the historical H56 TIFF has 1.0 px minimum nearest-neighbour spacing, and the transfer-calibrated values are not organizer scores.</p>'
        '<p class="muted">Every row is measured with the official distance-weighted Tversky '
        "definition on the independent off-catalogue frame (USGS SGMC fault pixels more than 300 m "
        'from the given catalogue). "Modelled hidden" applies the transfer factor below to the '
        'measured credit per dot and caps the total at the calibrated hidden mass.</p>'
        "<table><tr><th>requested dots</th><th>off-catalogue DTI</th><th>matched uniform</th>"
        f"<th>lift</th><th>credit / dot</th><th>modelled hidden DTI</th></tr>{rows}</table>"
        + ("<h3>Frozen blocked holdout, per macrofold</h3><table><tr><th>fold</th><th>candidate</th>"
           "<th>uniform</th><th>translation</th><th>dots in fold</th></tr>" + fold_rows + "</table>"
           if fold_rows else "")
        + '<p class="small">The transfer factor is measured on the group\'s own scored artifacts: '
        "the only structured artifacts available transfer at 3.97&ndash;4.59, and the one "
        "structureless artifact transfers at exactly 1.00, the mathematical expectation for a "
        "detector with no information. H56 uses the conservative 4.2. <b>This is the largest single "
        "uncertainty in the modelled number</b> and it is an assumption, not a measurement of "
        "H56.</p></article></div></div></section></main>"
    )


def main() -> None:
    report, unique, artifacts = load()
    h54 = load_h54()
    pages = {
        "index.html": overview(report, unique, artifacts),
        "results.html": results_page(report, unique, h54),
        "methods.html": methods_page(report),
        "submission.html": submission_page(report, artifacts, h54),
        "site.css": CSS,
    }
    for name, content in pages.items():
        path = ROOT / name
        path.write_text(content.rstrip() + "\n", encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)} ({path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
